name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinxcontrib-napoleon

    - name: Generate Sphinx configuration
      run: |
        mkdir -p docs
        cd docs
        sphinx-quickstart -q -p "ProjectName" -a "AuthorName" -v "0.1" --sep --ext-autodoc --makefile --batchfile
        echo "import os" >> conf.py
        echo "import sys" >> conf.py
        echo "sys.path.insert(0, os.path.abspath('../src'))" >> conf.py
        echo "extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon']" >> conf.py
        echo ".. toctree::" > index.rst
        echo "   :maxdepth: 2" >> index.rst
        echo "   :caption: Contents:" >> index.rst
        echo "" >> index.rst
        echo ".. automodule:: sma.utils.np_convert" >> index.rst
        echo "   :members:" >> index.rst
        echo "" >> index.rst
        echo ".. automodule:: sma.plot.scatter" >> index.rst
        echo "   :members:" >> index.rst
        echo "" >> index.rst
        echo ".. automodule:: sma.cluster.kmeans" >> index.rst
        echo "   :members:" >> index.rst

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "admin-gd"
        git config --global user.email "admin@gd.edu.kg"
        git clone --single-branch --branch gh-pages https://github.com/GitData-GA/shot-marilyns-analysis.git gh-pages-temp
        cd gh-pages-temp
        mkdir -p api-documentation
        cp -r ../docs/build/html/* api-documentation/
        git checkout -b gh-pages-temp
        git add api-documentation
        git commit -m 'Update Sphinx documentation'
        git push -u origin gh-pages-temp:gh-pages
